CREATE USER book
IDENTIFIED BY 1234;

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO book;


ALTER USER book DEFAULT TABLESPACE USERS;


ALTER USER book TEMPORARY TABLESPACE TEMP;


GRANT CREATE VIEW TO book;

GRANT CREATE TABLE TO book;